### ISSUE TITLE
Erreurs lors de l'initialisation du projet

### ISSUE THREAD

**Issue by vinyll** [betagouv/territoires-en-transitions#1524]
```
git clone git@github.com:betagouv/territoires-en-transitions.git
cd territoires-en-transitions
docker-compose up --build
```

### Sortie au 1er lanncement

```
➜  territoires-en-transitions git:(main) docker-compose up --build
Docker Compose is now in the Docker CLI, try `docker compose up`

Creating network "territoires-en-transitions_default" with the default driver
Building client
[+] Building 318.1s (10/11)
 => [internal] load build definition from Dockerfile                                                                                                                                0.1s
 => => transferring dockerfile: 208B                                                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                                                   0.0s
 => => transferring context: 68B                                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/node:14.15.1-alpine                                                                                                              5.0s
 => [1/6] FROM docker.io/library/node:14.15.1-alpine@sha256:d41417bb7fd04744cd159a40632f918c13bc1af3486a848782e1f68af2c3e6cb                                                       76.0s
 => => resolve docker.io/library/node:14.15.1-alpine@sha256:d41417bb7fd04744cd159a40632f918c13bc1af3486a848782e1f68af2c3e6cb                                                        0.0s
 => => sha256:d41417bb7fd04744cd159a40632f918c13bc1af3486a848782e1f68af2c3e6cb 1.43kB / 1.43kB                                                                                      0.0s
 => => sha256:05a2f563ff66492dbe3c82cb482d6c1bbaecefcac4d42bd3744c7693028c9e44 1.16kB / 1.16kB                                                                                      0.0s
 => => sha256:7f1893c3ede08c41f7e55c7a2a68fe115c6f1c9b2d5375cd4c4b26fab504170a 6.73kB / 6.73kB                                                                                      0.0s
 => => sha256:cbdbe7a5bc2a134ca8ec91be58565ec07d037386d1f1d8385412d224deafca08 2.81MB / 2.81MB                                                                                     10.1s
 => => sha256:f2ffd52523c3c53242323a6259d0775306d5d3293c223b73a25ebe45cc855cfe 36.00MB / 36.00MB                                                                                   67.2s
 => => sha256:48a445fb9d78e4fe7356b01031e5eee9ba5a3229a24d4d06c1c0e68271f51921 2.24MB / 2.24MB                                                                                     10.2s
 => => extracting sha256:cbdbe7a5bc2a134ca8ec91be58565ec07d037386d1f1d8385412d224deafca08                                                                                           1.2s
 => => sha256:7a27e63388b243ea1e750aba171f05f71fb9df23ab31dea9d049a4207fec4ae4 280B / 280B                                                                                         10.6s
 => => extracting sha256:f2ffd52523c3c53242323a6259d0775306d5d3293c223b73a25ebe45cc855cfe                                                                                           7.5s
 => => extracting sha256:48a445fb9d78e4fe7356b01031e5eee9ba5a3229a24d4d06c1c0e68271f51921                                                                                           0.5s
 => => extracting sha256:7a27e63388b243ea1e750aba171f05f71fb9df23ab31dea9d049a4207fec4ae4                                                                                           0.0s
 => [internal] load build context                                                                                                                                                   0.7s
 => => transferring context: 6.68MB                                                                                                                                                 0.6s
 => [2/6] WORKDIR /app                                                                                                                                                              0.0s
 => [3/6] COPY ./package.json ./                                                                                                                                                    0.0s
 => [4/6] COPY ./package-lock.json ./                                                                                                                                               0.0s
 => [5/6] RUN npm install                                                                                                                                                         189.4s
 => [6/6] COPY . .                                                                                                                                                                  0.3s
 => exporting to image                                                                                                                                                             46.9s
 => => exporting layers                                                                                                                                                            46.9s
cannot write /var/folders/kh/l4pck1457qq4x1fqp1k7m55m0000gn/T/tmpxdcuc706 because server did not provide an image ID
ERROR: Service 'client' failed to build : Build failed
```

### 2e essai

```
docker-compose up --build
```

Sortie :
```
➜  territoires-en-transitions git:(main) docker-compose up --build
Docker Compose is now in the Docker CLI, try `docker compose up`

Building client
[+] Building 66.4s (11/11) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                0.0s
 => => transferring dockerfile: 37B                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                   0.0s
 => => transferring context: 34B                                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/node:14.15.1-alpine                                                                                                              6.5s
 => [1/6] FROM docker.io/library/node:14.15.1-alpine@sha256:d41417bb7fd04744cd159a40632f918c13bc1af3486a848782e1f68af2c3e6cb                                                        0.0s
 => [internal] load build context                                                                                                                                                   0.1s
 => => transferring context: 18.11kB                                                                                                                                                0.1s
 => CACHED [2/6] WORKDIR /app                                                                                                                                                       0.0s
 => CACHED [3/6] COPY ./package.json ./                                                                                                                                             0.0s
 => CACHED [4/6] COPY ./package-lock.json ./                                                                                                                                        0.0s
 => CACHED [5/6] RUN npm install                                                                                                                                                    0.0s
 => CACHED [6/6] COPY . .                                                                                                                                                           0.0s
 => exporting to image                                                                                                                                                             59.6s
 => => exporting layers                                                                                                                                                            59.6s
 => => writing image sha256:c7561f1a9ad23eae90f2a100e0fddbf1b549488af193f6660fc318b6f890bc4d                                                                                        0.0s
 => => naming to docker.io/library/territoires-en-transitions_client                                                                                                                0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Pulling postgres (postgres:12)...
12: Pulling from library/postgres
5eb5b503b376: Pull complete
daa0467a6c48: Pull complete
7cf625de49ef: Pull complete
bb8afcc973b2: Pull complete
c74bf40d29ee: Pull complete
2ceaf201bb22: Pull complete
1255f255c0eb: Pull complete
12a9879c7aa1: Pull complete
f7ca80cc6dd3: Pull complete
6714db455645: Pull complete
ee4f5626bf60: Pull complete
621bb0c2ae77: Pull complete
a19e980f0a72: Pull complete
Digest: sha256:91f425179c75df828c1979af77bb49c1042f5f24b46998b44551da0b3a2e0a5e
Status: Downloaded newer image for postgres:12
Building api
[+] Building 241.1s (9/10)
[+] Building 292.5s (11/11) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                0.1s
 => => transferring dockerfile: 279B                                                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                                                   0.0s
 => => transferring context: 2B                                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/python:3.9                                                                                                                       4.0s
 => [1/6] FROM docker.io/library/python:3.9@sha256:1fb89e1a6f8e739f2a274e745b80d11b1fdad72860489c1794ef13aa5fd69f94                                                               127.2s
 => => resolve docker.io/library/python:3.9@sha256:1fb89e1a6f8e739f2a274e745b80d11b1fdad72860489c1794ef13aa5fd69f94                                                                 0.0s
 => => sha256:2cb8a75336f5278c9c6ce305acb3891358227a6c5abd08a0db6f2b7633ff6812 8.54kB / 8.54kB                                                                                      0.0s
 => => sha256:0c6b8ff8c37e92eb1ca65ed8917e818927d5bf318b6f18896049b5d9afc28343 54.92MB / 54.92MB                                                                                   86.9s
 => => sha256:1fb89e1a6f8e739f2a274e745b80d11b1fdad72860489c1794ef13aa5fd69f94 2.35kB / 2.35kB                                                                                      0.0s
 => => sha256:c59372055ab5f8f22b21964a58d5d7a2df1b7a09f10c18a687cb93f548ffe76c 2.22kB / 2.22kB                                                                                      0.0s
 => => sha256:412caad352a3ecbb29c080379407ae0761e7b9b454f7239cbfd1d1da25e06b29 5.15MB / 5.15MB                                                                                      9.6s
 => => sha256:e6d3e61f7a504fa66d7275123969e9917570188650eb84b2280a726b996040f6 10.87MB / 10.87MB                                                                                   14.7s
 => => sha256:461bb1d8c517c7f9fc0f1df66c9dc34c85a23421c1e1c540b2e28cbb258e75f5 54.57MB / 54.57MB                                                                                   80.7s
 => => sha256:808edda3c2e855dc13af758b35cefbcc417ad1ab4fead7f72234b09aeda893a0 196.53MB / 196.53MB                                                                                109.2s
 => => sha256:724cfd2dc19be12b837643ea67bd5ad7a6fd98049a88f02ec70eca30fa03a5a1 6.29MB / 6.29MB                                                                                     83.5s
 => => sha256:154165346525714a14f08db2194115601362b194b2190a787a71b719eca5f45e 17.75MB / 17.75MB                                                                                   88.4s
 => => sha256:064e2bb896fa806f202675b275bf04a16479b367f8d4938774e22d1154bc7c34 240B / 240B                                                                                         87.2s
 => => extracting sha256:0c6b8ff8c37e92eb1ca65ed8917e818927d5bf318b6f18896049b5d9afc28343                                                                                           5.6s
 => => sha256:b2cc9d2f64ab864b81a9805e399921717277a2a21f0e75e8cd9ad224db5da16a 2.34MB / 2.34MB                                                                                     88.3s
 => => extracting sha256:412caad352a3ecbb29c080379407ae0761e7b9b454f7239cbfd1d1da25e06b29                                                                                           0.5s
 => => extracting sha256:e6d3e61f7a504fa66d7275123969e9917570188650eb84b2280a726b996040f6                                                                                           0.8s
 => => extracting sha256:461bb1d8c517c7f9fc0f1df66c9dc34c85a23421c1e1c540b2e28cbb258e75f5                                                                                           6.2s
 => => extracting sha256:808edda3c2e855dc13af758b35cefbcc417ad1ab4fead7f72234b09aeda893a0                                                                                          13.6s
 => => extracting sha256:724cfd2dc19be12b837643ea67bd5ad7a6fd98049a88f02ec70eca30fa03a5a1                                                                                           0.5s
 => => extracting sha256:154165346525714a14f08db2194115601362b194b2190a787a71b719eca5f45e                                                                                           1.2s
 => => extracting sha256:064e2bb896fa806f202675b275bf04a16479b367f8d4938774e22d1154bc7c34                                                                                           0.0s
 => => extracting sha256:b2cc9d2f64ab864b81a9805e399921717277a2a21f0e75e8cd9ad224db5da16a                                                                                           0.3s
 => [internal] load build context                                                                                                                                                   0.3s
 => => transferring context: 2.91MB                                                                                                                                                 0.2s
 => [2/6] WORKDIR /api                                                                                                                                                              0.1s
 => [3/6] COPY . .                                                                                                                                                                  0.1s
 => [4/6] RUN pip install -U pipenv                                                                                                                                                19.5s
 => [5/6] RUN pipenv install                                                                                                                                                       76.4s
 => [6/6] RUN pipenv install --dev                                                                                                                                                 60.4s
 => exporting to image                                                                                                                                                              4.6s
 => => exporting layers                                                                                                                                                             4.6s
 => => writing image sha256:c18cf8099325541047d5ec8450fc30e99c73efa772e942c04bf7e44ad5e9b05b                                                                                        0.0s
 => => naming to docker.io/library/territoires-en-transitions_api                                                                                                                   0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Pulling adminer (adminer:)...
latest: Pulling from library/adminer
59bf1c3509f3: Already exists
7c7da25b2876: Already exists
2bc599114627: Already exists
927a0b37a45a: Already exists
d47c8877a66a: Pull complete
8f3c2cc92d11: Pull complete
05db1cf8b390: Pull complete
d1140d7e4ba0: Pull complete
887b804c743a: Pull complete
17413dba47a0: Pull complete
e18e50dd401d: Pull complete
111cd0fb20a3: Pull complete
2e9e829195f7: Pull complete
50d72130afd0: Pull complete
6003b0cb4252: Pull complete
Digest: sha256:bbecfea5b1bafbe2057ce53996463f349daaa01198215e14a498a4a9c428f0ff
Status: Downloaded newer image for adminer:latest
Creating territoires-en-transitions_adminer_1  ... done
Creating territoires-en-transitions_client_1   ... done
Creating territoires-en-transitions_postgres_1 ... done
Creating territoires-en-transitions_api_1      ... done
Attaching to territoires-en-transitions_postgres_1, territoires-en-transitions_adminer_1, territoires-en-transitions_client_1, territoires-en-transitions_api_1
adminer_1   | [Tue Mar  1 22:01:28 2022] PHP 7.4.28 Development Server (http://[::]:8080) started
client_1    |
client_1    | > app.territoiresentransitions.react@0.1.0 dev /app
client_1    | > craco start
client_1    |
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  |
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  |
postgres_1  | Data page checksums are disabled.
postgres_1  |
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1  | creating subdirectories ... ok
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | selecting default max_connections ... 100
postgres_1  | selecting default shared_buffers ... 128MB
postgres_1  | selecting default time zone ... Etc/UTC
postgres_1  | creating configuration files ... ok
api_1       | 2022-03-01 22:01:38.107 | INFO     | __main__:serve:9 - Running uvicorn on 8000
postgres_1  | running bootstrap script ... ok
api_1       | Traceback (most recent call last):
api_1       |   File "/api/server.py", line 14, in <module>
api_1       |     serve()
api_1       |   File "/api/server.py", line 10, in serve
api_1       |     uvicorn.run("api.app:app", host="0.0.0.0", port=PORT, workers=1)
api_1       |   File "/root/.local/share/virtualenvs/api-ORERwo9D/lib/python3.9/site-packages/uvicorn/main.py", line 447, in run
api_1       |     server.run()
api_1       |   File "/root/.local/share/virtualenvs/api-ORERwo9D/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
api_1       |     return asyncio.run(self.serve(sockets=sockets))
api_1       |   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
api_1       |     return loop.run_until_complete(main)
api_1       |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
api_1       |     return future.result()
api_1       |   File "/root/.local/share/virtualenvs/api-ORERwo9D/lib/python3.9/site-packages/uvicorn/server.py", line 76, in serve
api_1       |     config.load()
api_1       |   File "/root/.local/share/virtualenvs/api-ORERwo9D/lib/python3.9/site-packages/uvicorn/config.py", line 448, in load
api_1       |     self.loaded_app = import_from_string(self.app)
api_1       |   File "/root/.local/share/virtualenvs/api-ORERwo9D/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
api_1       |     module = importlib.import_module(module_str)
api_1       |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
api_1       |     return _bootstrap._gcd_import(name[level:], package, level)
api_1       |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
api_1       |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
api_1       |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
api_1       |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
api_1       |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
api_1       |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
api_1       |   File "/api/api/app.py", line 6, in <module>
api_1       |     from api.routers.v2 import (
api_1       |   File "/api/api/routers/v2/statistics.py", line 229, in <module>
api_1       |     query = InMemoryQuery() if "sqlite" in DATABASE_URL else PostgresQuery()
api_1       |   File "/api/api/routers/v2/statistics.py", line 137, in __init__
api_1       |     self._connection = self.get_new_connection()
api_1       |   File "/api/api/routers/v2/statistics.py", line 140, in get_new_connection
api_1       |     return psycopg2.connect(**self._connection_kwargs)
api_1       |   File "/root/.local/share/virtualenvs/api-ORERwo9D/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
api_1       |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
api_1       | psycopg2.OperationalError: could not connect to server: Connection refused
api_1       | 	Is the server running on host "postgres" (172.18.0.3) and accepting
api_1       | 	TCP/IP connections on port 5432?
api_1       |
territoires-en-transitions_api_1 exited with code 1
client_1    | Browserslist: caniuse-lite is outdated. Please run:
client_1    |   npx browserslist@latest --update-db
client_1    |   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
postgres_1  | performing post-bootstrap initialization ... ok
postgres_1  | syncing data to disk ... ok
postgres_1  |
postgres_1  | initdb: warning: enabling "trust" authentication for local connections
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
postgres_1  |
postgres_1  | Success. You can now start the database server using:
postgres_1  |
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1  |
postgres_1  | waiting for server to start....2022-03-01 22:01:59.846 UTC [48] LOG:  starting PostgreSQL 12.10 (Debian 12.10-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
postgres_1  | 2022-03-01 22:01:59.879 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2022-03-01 22:01:59.969 UTC [49] LOG:  database system was shut down at 2022-03-01 22:01:54 UTC
postgres_1  | 2022-03-01 22:02:00.040 UTC [48] LOG:  database system is ready to accept connections
postgres_1  |  done
postgres_1  | server started
client_1    | ℹ ｢wds｣: Project is running at http://172.18.0.4/
client_1    | ℹ ｢wds｣: webpack output is served from
client_1    | ℹ ｢wds｣: Content not from webpack is served from /app/public
client_1    | ℹ ｢wds｣: 404s will fallback to /
client_1    | Starting the development server...
client_1    |
postgres_1  | CREATE DATABASE
postgres_1  |
postgres_1  |
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  |
postgres_1  | 2022-03-01 22:02:03.529 UTC [48] LOG:  received fast shutdown request
postgres_1  | waiting for server to shut down...2022-03-01 22:02:03.533 UTC [48] LOG:  aborting any active transactions
postgres_1  | 2022-03-01 22:02:03.541 UTC [48] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
postgres_1  | .2022-03-01 22:02:03.557 UTC [50] LOG:  shutting down
postgres_1  | 2022-03-01 22:02:03.634 UTC [48] LOG:  database system is shut down
postgres_1  |  done
postgres_1  | server stopped
postgres_1  |
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  |
postgres_1  | 2022-03-01 22:02:03.701 UTC [1] LOG:  starting PostgreSQL 12.10 (Debian 12.10-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
postgres_1  | 2022-03-01 22:02:03.701 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2022-03-01 22:02:03.701 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2022-03-01 22:02:03.744 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2022-03-01 22:02:03.830 UTC [76] LOG:  database system was shut down at 2022-03-01 22:02:03 UTC
postgres_1  | 2022-03-01 22:02:03.890 UTC [1] LOG:  database system is ready to accept connections
client_1    |
client_1    |                     The build failed because the process exited too early.
client_1    |                     This probably means the system ran out of memory or someone called
client_1    |                     `kill -9` on the process.
client_1    |
client_1    | npm ERR! code ELIFECYCLE
client_1    | npm ERR! errno 1
client_1    | npm ERR! app.territoiresentransitions.react@0.1.0 dev: `craco start`
client_1    | npm ERR! Exit status 1
client_1    | npm ERR!
client_1    | npm ERR! Failed at the app.territoiresentransitions.react@0.1.0 dev script.
client_1    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
client_1    |
client_1    | npm ERR! A complete log of this run can be found in:
client_1    | npm ERR!     /root/.npm/_logs/2022-03-01T22_02_58_556Z-debug.log
territoires-en-transitions_client_1 exited with code 1
postgres_1  | 2022-03-01 22:08:04.400 UTC [80] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted
postgres_1  | 2022-03-01 22:13:04.617 UTC [80] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted
```

La même erreur survient en lançant `docker-compose up`

Le service n'est pas disponible sur http://localhost:3001 ni http://localhost:3000

**Comment by Emelinejy** [comment]
@derfurth tu pourras regarder quand tu auras quelques minutes ?

**Comment by thom4parisot** [comment]
J'ai l'impression que ça arrive lorsque l'app API s'initialise avant que la base de données aie eu le temps d'être opérationnelle.

Une fois cette étape passée, j'ai bien une appli qui fonctionne (il faut ouvrir le port 8000 de l'API également pour qu'elle soit joignable — cf. toujours la même pull request) mais je rame à me connecter.

En réglant la variable d'environnement `AUTH_DISABLED_DUMMY_USER` à `YES` dans le `docker-compose.yaml`, je suis toujours redirigé vers la mire de connexion "moncompte.ademe.fr" alors que je m'attendais à un écran local (ou autre) qui me permette de saisir des identifiants bidon. Idem lorsque je tente de créer un compte.

Je suis bien chaud pour tenter de simuler un PCAET pour ma communauté de commune, mais en tant que citoyen seulement.
